# version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/ssl/tymchenko.fr_ssl_certificate.cer:/etc/ssl/certs/tymchenko.fr_ssl_certificate.cer:ro
      - ./nginx/ssl/_.tymchenko.fr_private_key.key:/etc/ssl/private/_.tymchenko.fr_private_key.key:ro
      - ./nginx/web:/usr/share/nginx/html:ro

    depends_on:
      - api
      - phpmyadmin
      - auth
      - pgadmin
      - mind
      # - frontend
    networks:
      - journalsNode
  # frontend:
  #   build: ./frontend
  #   volumes:
  #     - /home/M_10_a/frontend:/usr/src/app
  #   environment:
  #     - PUBLIC_URL=/frontend
  #   networks:
  #     - journalsNode
  mind:
    build: ./mind
    depends_on:
      - mind_db
    volumes:
      - ${PROJECT_PATH}/mind:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - OPEN_AI_API=${OPEN_API}
      - POSTGRES_DB=${MIND_PG_DB}
      - POSTGRES_USER=${MIND_PG_USER}
      - POSTGRES_PASSWORD=${MIND_PG_PASSWORD}
    networks:
      - journalsNode

  mind_db:
    container_name: mind_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${MIND_PG_DB}
      POSTGRES_USER: ${MIND_PG_USER}
      POSTGRES_PASSWORD: ${MIND_PG_PASSWORD}
    volumes:
      - mind_pgdata:/var/lib/postgresql/data
    networks:
      - journalsNode

  api:
    build: ./api
    depends_on:
      - db
    volumes:
      - ${PROJECT_PATH}/api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - journalsNode
  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - journalsNode
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - PMA_ABSOLUTE_URI=https://tymchenko.fr/phpmyadmin/
    networks:
      - journalsNode
  auth:
    build: ./auth
    depends_on:
      - auth_db
    volumes:
      - ${PROJECT_PATH}/auth:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres:// ${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - journalsNode
  auth_db:
    container_name: auth_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - journalsNode
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - auth_db
      - mind_db
    networks:
      - journalsNode
networks:
  journalsNode:
    name: journalsNode
    driver: bridge
volumes:
  dbdata:
  pgdata:
  mind_pgdata:
