GET http://brigitte.bwb/api/articles/59
###
GET http://brigitte.bwb/api/articles/delete/58
###"
###"

GET http://brigitte.bwb/api/articles/

####

POST http://brigitte.bwb/api/addArticle
Content-Type: application/json
{
    "author": "API TEST",
    "userId": 2,
    "title": "MORINING JEUDI",
    "description": "LETS TRY",
}