###
POST /auth/login HTTP/1.1
Host: https://tymchenko.fr/
Content-Type: application/json

{
    "username": "prerOK",
    "password": "321"
}
####

###
POST /auth/register HTTP/1.1
Host: https://tymchenko.fr/auth/
Content-Type: application/json

{
    "username": "frenchMan2",
    "password": "userpassword",
    "email":"another@email.route"
}
####

GET /auth/users HTTP/1.1
Host: https://tymchenko.fr/auth/

####
####

GET /auth/users/17 HTTP/1.1
Host: https://tymchenko.fr/auth/

####
####

DELETE /auth/users/17 HTTP/1.1
Host: localhost:3000

####
####

PATCH /auth/users/update/16 HTTP/1.1
Host: localhost:3000
Content-Type: application/json

{
  
    "username": "prerOK456",
    "email":"drufddfdfdfder@email.route",
    "password":"321"
}
####