version: '3.8'
services:
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl/cert.pem:/etc/ssl/cert.pem:ro
      - ./ssl/privkey.pem:/etc/ssl/privkey.pem:ro
  symfony:
    build: ./symfony
    ports:
      - '8080:80'
    depends_on:
      - db
    volumes:
      - /home/M_10_a/symfony:/var/www/html/
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:3306/${MYSQL_DB}
    networks:
      - journalsNode
  api:
    build: ./api
    ports:
      - '80:3001'
    depends_on:
      - db
    volumes:
      - /home/M_10_a/api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MYSQL_DB=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - journalsNode
  db:
    image: mysql:8.0.36
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - journalsNode
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '81:80'
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - journalsNode
  auth:
    build: ./auth
    ports:
      - '3000:3000'
    depends_on:
      - auth_db
    volumes:
      - /home/M_10_a/auth:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - DATABASE_URL=postgres:// ${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    networks:
      - journalsNode
  auth_db:
    container_name: auth_db
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - journalsNode
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - '5050:80'
    depends_on:
      - auth_db
    networks:
      - journalsNode
networks:
  journalsNode:
volumes:
  dbdata:
  pgdata:
